### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by MartyLake** [tbabej/taskwiki#145] opened 2017-05-22 13:16 UTC
Hi !

I had a setup into ubuntu bash for windows10, that involved managing tasks from a *work* vim wiki page using your magnificent plugin :) I updated the bash for windows 10, installed all the missing stuff (python3-pip, task python lib, vim, etc.). But now I have an error when loading the work wiki page telling me that:

Invalid JSON

It appears twice. When I press ENTER to continue, I can read the page but taskwiki is disabled.

Do you have any idea what's happening ?
Best,

**Comment by tbabej** [comment] 2017-05-23 12:44
"Invalid JSON" is raised by tasklib in tasklib/backends.py:323. Since you have no data in your error message, that would suggest an empty line in the output of the "task export", which is kind of weird. You can try hotfixing by skipping over empty lines, like this:

    if not data.strip():
        continue

But I would rather see you digging down to see what's the cause of that empty line.

**Comment by MartyLake** [comment] 2017-05-24 15:28
Well, I have a lot of data but I don't know how to copy it here !

It's romething like:

```
raise TaskWarriorException('Invalid JSON: %s. % data)
tasklib.backends.TaskWarriorException: Invalid JSON: {"id":11 … etc.
```

**Comment by MartyLake** [comment] 2017-05-24 15:45
here is "task 11" output attached :

[task11.txt](https://github.com/tbabej/taskwiki/files/1026142/task11.txt)

**Comment by tbabej** [comment] 2017-05-24 21:56
Can you provide the output of `task 11 export` instead?

**Comment by MartyLake** [comment] 2017-05-31 08:29
Here you go!

[task11export.txt](https://github.com/tbabej/taskwiki/files/1040719/task11export.txt)

**Comment by tbabej** [comment] 2017-05-31 09:48
Well, you can clearly see that the JSON is malformed - the depends attribute is invalid (contains double " without escaping). It seems that your data was malformed by some third party, task itself (unlikely, if so, then it's a bug), some mobile app or hook.

After fixing the invalid data taskwiki should work just fine. Closing as invalid for now, feel free to reopen if the issue remains.

**Closed by tbabej** 2017-05-31 09:48 UTC

**Comment by MartyLake** [comment] 2017-05-31 11:15
I created and manipulated this task using taskwiki. Maybe it comes from
there ? This was a main task, and I opened (and closed) a lot of depending
tasks for this one.

I don't know how to "fix invalid data", do you have any resource regarding
this ?


---
Matthieu TALBOT
neogaldr@gmail.com

+33 629 22 15 70
fr.linkedin.com/in/matthieutalbot
http://www.soundcloud.com/Marty-Lake
http://lifehacker.com/5028808/how-eom-makes-your-email-more-efficient

**Comment by tbabej** [comment] 2017-05-31 11:21
Fixing the invalid data means manually editing the data files of taskwarrior so that the "depends" field is properly formed. It should be a list of UUIDs, surely, you have other tasks that are well formed that can serve as reference.

If not, I recommend starting with an empty test taskwarrior database to see how the data should look like and then edit the original data accordingly.

Here is an example from my data:

    [component:"MLThesis" depends:"f014ed1a-1f2c-4fab-a082-5d83beb03a03,9acb36d3-bb27-4181-9c7b-d34d3c9d6531" description:"Improve framework" entry:"1479436529" modified:"1479436529" project:"Education.School" status:"pending" uuid:"11558ebb-eddf-410d-8b1f-de2a0f5b72eb"]

I suspect your depends field will look like

    depends:"["50d604b0-efe6-4bc2-82a6-4f2da8ac3688"",""5b6b6e9e-0a8c-48f1-87a9-77d4af57636c"",""5703143e-06f3-4998-a949-3cc8531950c0"",""8c4e0039-59c8-4301-bf9e-ae972f98d964"",""7d9297ce-749c-4bad-b899-404dc7e1f240"",""372a1134-d0ea-4cac-8fe1-a33f5629dacf"",""30bf310b-79cc-4642-92c9-6468fab17428"",""209d9d6a-59df-4205-be52-1e462ec33ac1"]"

instead.

**Comment by MartyLake** [comment] 2017-05-31 11:22
Also, I don't have this problem on my other computer. Only on the work computer (which I used heavily to work on this "main task", and depending ones.)

Thanks, I will try on fix it manually and import it back.

**Comment by MartyLake** [comment] 2017-05-31 11:25
The fix worked. But now I also have an issue with task 0 (also the depends field)

**Comment by MartyLake** [comment] 2017-05-31 11:28
Fixed task 0 (I had to use it's uuid to export it) and now it's ok. I will just stop using depends from now on :) thanks for all your time @tbabej and thanks for your awesome extension, I was so sad to have to stop using it !!!

**Comment by tbabej** [comment] 2017-05-31 11:33
Glad to see you got it working. If the issue comes up again (and you're sure it wasn't caused by some other tool), let me know. I'd be interested to hear more if you could come up with a reproducer.

**Comment by MartyLake** [comment] 2017-05-31 12:08
the only tools I use are:
- task
- tasksh (review)
- taskwiki

If I've got a reproducer, I'll contact you for sure ! Have a good day !
