### ISSUE TITLE
Not working with markdown file?

### ISSUE THREAD

**Issue by tnguyen14** [tbabej/taskwiki#109] opened 2016-12-15 22:58 UTC
Hi,

I am new to taskwarrior and vimwiki, and got quite excited when I saw taskwiki and wanted to give it a try.

In my `index.md` file, I just added a single task as 

```md
## Todos

- [ ] example task
```

However, upon saving the file, I don't see the task. That is, going back to the CLI:

```
:; task
[task next]
No matches.
```

Not sure if I am doing something wrong here? Does taskwiki work with the markdown format?

**Comment by tbabej** [comment] 2016-12-15 23:42
We've grown out of mediawiki syntax, so currently only

    * [ ] example task

is supported. The addition of markdown would not be a huge task, just two things are needed:

1. Extension of regexes for header and task in `regexp.py`
2. Improve string representations of tasks in the buffer to support markdown syntax

**Comment by linuxcaffe** [comment] 2016-12-16 01:55
this vimwiki discussion is related, I think; https://github.com/vimwiki/vimwiki/issues/15#issuecomment-267397004

**Comment by tnguyen14** [comment] 2016-12-17 22:13
@tbabej I see.

I tried with the ` * [ ] example task` syntax as well, but it doesn't work either.

Does the file format or extension (`.md`) have any impact?

**Comment by tnguyen14** [comment] 2016-12-17 22:22
So a bit of an update: after switching to `*`, I see the task ID (?) being added to each line, such as `#33b0d0a9`, but `$ task next` still returns `No matches.` Maybe something is not hooked up properly?

**Comment by tbabej** [comment] 2016-12-17 22:46
That sounds interesting. What does:

    $ task 33b0d0a9 info

show?

**Comment by tnguyen14** [comment] 2016-12-17 23:17
```
$ task 33b0d0a9 info
No matches.
```

**Comment by tbabej** [comment] 2016-12-17 23:27
Are you running both processes under the same user? Let's see if you're data.location is the same:

task:

    $ task _get rc.data.location

taskwiki (make sure you have a vimwiki file open):

    :py print(cache.get_relevant_tw().config['data.location'])

**Comment by tnguyen14** [comment] 2016-12-18 00:04
Ah! that might be it. I have a custom location for `task`, but taskwiki is using the default. Do I need to set taskwiki's location separately?

**Comment by tbabej** [comment] 2016-12-18 00:11
Yes, using `taskwiki_data_location`:

    let g:taskwiki_data_location="/my/alternative/location"

but we should probably respect what's in the taskrc already. Let's keep this open as a reminder.

**Comment by tbabej** [comment] 2016-12-18 00:16
I just pushed a commit that should make it work even without this setting. Maybe you can update&test?

**Comment by tnguyen14** [comment] 2016-12-18 00:29
I just updated and got the following error:

```
UUID '33b0d0a9' not found, Task on line 9 will be re-created in TaskWarrior.
Error detected while processing function provider#python#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tri.nguyen/.vim/plugged/taskwiki/taskwiki/main.py", line 52, in update_to_tw
    cache.save_tasks()
  File "/Users/tri.nguyen/.vim/plugged/taskwiki/taskwiki/cache.py", line 129, in save_tasks
    task.save_to_tw()
  File "/Users/tri.nguyen/.vim/plugged/taskwiki/taskwiki/vwtask.py", line 262, in save_to_tw
    self.task.save()
  File "/usr/local/lib/python2.7/site-packages/tasklib/task.py", line 405, in save
    self.backend.save_task(self)
  File "/usr/local/lib/python2.7/site-packages/tasklib/backends.py", line 351, in save_task
    task.refresh(after_save=True)
  File "/usr/local/lib/python2.7/site-packages/tasklib/task.py", line 429, in refresh
    new_data = self.backend.refresh_task(self, after_save=after_save)
  File "/usr/local/lib/python2.7/site-packages/tasklib/backends.py", line 411, in refresh_task
    task['uuid'] or task['id'], task['description'], output)
```

**Comment by tbabej** [comment] 2016-12-18 00:38
The output is truncated - the most important line (what kind of error) is missing (unfortunately this happens always in vim). Could you please run:

    :messages

and paste it here?

**Comment by tnguyen14** [comment] 2016-12-18 00:44
@tbabej I've updated the comment with the error above.

**Comment by tbabej** [comment] 2016-12-18 00:58
Very puzzling. This error message seems to indicate that there are multiple tasks in your database with an ID '1'. Is this reproducible (happens every time)?

What does your ``task export`` show? (censor out private data, if any)

**Comment by tnguyen14** [comment] 2016-12-18 01:10
Yes this is reproducible on every save.

```
$ task export
[
]
```

**Comment by tbabej** [comment] 2016-12-18 01:34
Does it work if you set the 

    let g:taskwiki_data_location="/my/alternative/location"

in your `.vimrc`?

**Comment by tbabej** [comment] 2016-12-18 01:35
Just making sure: Are you using custom location for `~/.taskrc` as well?

**Comment by tnguyen14** [comment] 2016-12-18 01:43
My taskrc is at ~/.taskrc.

The error seems to be away if I set it in `.vimrc`.

The other thing that might be odd is the data location has a space in it, .i.e `~/Google\ Drive`.

And even with setting the `g:taskwiki_data_location`, `task next` is still `No matches.`

**Comment by tbabej** [comment] 2016-12-18 02:26
The space **might** be it, but I can't reproduce. Can we get the data location in ~/.taskrc and as seen by taskwiki (both without the g:taskwiki_data_location) and with it?

**Comment by tnguyen14** [comment] 2016-12-18 03:02
How should I get that data for you?

**Comment by tbabej** [comment] 2016-12-18 10:04
You can use my email (just published it on my profile).

**Comment by tbabej** [comment] 2017-01-09 00:39
This boiled down to a (still unresolved) taskwarrior (not taskwiki) issue, so I'm closing it for the time being.

**Closed by tbabej** 2017-01-09 00:39 UTC

**Comment by tnguyen14** [comment] 2017-01-09 15:57
FYI, this is the link to the taskwarrior issue https://bug.tasktools.org/browse/TW-1879

**Comment by tnguyen14** [comment] 2017-01-10 03:45
Removing the `\` in the data location path (so just `~/Google Drive/Notes/Task`) seems to fix that issue.

**Comment by tbabej** [comment] 2017-01-10 17:07
Nice to see that you figured this out. I'll edit the title accordingly.
