### ISSUE TITLE
Can not create new link with enter in normal mode

### ISSUE THREAD

**Issue by canaaerus** [tbabej/taskwiki#117] opened 2017-01-19 19:55 UTC
During normal mode vimwiki allows to press _[enter]_ when over a word. Then that word is converted into a link, i.e. surrounded by double brackets. This is not possible anymore once taskwiki was installed.

I’m using vim 8.0.0106.

Btw. I’m also experiencing #116, but without any error messages.

**Comment by canaaerus** [comment] 2017-01-21 17:51
I don’t actually seem to use the taskwiki enter-mapping much. So my suggestion is the following:

* do not map enter to `Mappings.task_info_or_vimwiki_follow_link`
* merge `TaskWikiInfo` and `TaskWikiInspect`, because only one is applicable at any time
* map `<leader>ti` to the merged function

I tried to put `nmap <CR> <Plug>VimwikiFollowLink` into `~/.vim/after/ftplugin/vimwiki.vim` but that does not work. Any idea why?

**Comment by tbabej** [comment] 2017-01-26 21:52
Well, I do use it much! So it's a per-user thing I suppose :)

That said, merging TaskWikiInfo and TaskWikiInspect makes sense in any case. Changing the default Enter mapping seems like a workaround, we should find the core of the issue instead.

On the other hand, there might be a rare user that is used to using Enter for it's default function - moving down the screen. So another solution would be wrapping any no-`<leader>t` prefixed mappings in a if block controlled by a configuration variable.

**Comment by canaaerus** [comment] 2017-01-26 22:32
Ah yes, I did find the cause: `TaskWiki` overwrites the `enter` mapping and calls the `VimWiki` function, if it finds a link. Otherwise it tries to get the task info or inspect viewport. Now if there is no link, task or viewport it simply does nothing.

In that case it would be possible to also call `VimwikiFollowLink`. But I think that would be too inconsistent, because one might just as well want to create new links inside of tasks and viewport titles.

Your suggestion of using a configuration variable to give the user a choice of using the `vimwiki` binding or the one from `taskwiki` is probably the best solution. And maybe in its description we could add the alternative of using `enter` in visual mode (after `viw` e.g.; is that a standard binding?) for the `vimwiki` action.

**Comment by tbabej** [comment] 2017-01-27 09:50
I pushed a commit which fixes the issue of not creating a link on a non-linked-non-task-non-viewport line, since I consider that a bug. Thanks for noticing.

Links and viewports/tasks should really not be mixed. It creates a mess, task descriptions in TW suddenly contain `[[..]]` cruft, etc.

We can also go with an option, but I'm thinking more along the lines of `g:taskwiki_allowed_mappings = ['Enter,...']`, for any non-<Leader>-prefixed mapping. But since there is only `<Enter>` for now, this might be an overkill. Long story short, I will accept a PR with a option enhancement.

**Comment by BonarBeavis** [comment] 2017-01-30 15:51
Shouldn't be the default not to break vimwiki? As being taskwiki a extension for vimwiki, I think it is unexpected behaviour, if after installing taskwiki it, is not possible to follow links with `<CR>` anymore.

**Comment by tbabej** [comment] 2017-01-30 19:40
Unless you have outdated version of taskwiki (or placing links inside task descriptions / viewport headers), you should not have an issue.

**Comment by BonarBeavis** [comment] 2017-02-06 11:46
My version is not outdated. I looked into this, maybe the problem is, that I use markdown for vimwiki. My guess is there is a bug in [main.py](https://github.com/tbabej/taskwiki/blob/0225b44e536c1c9b2eb1e145979c715b2a399ea8/taskwiki/main.py#L243). The code never reaches the last line in the following snippet:

```viml
        # No link detected, check for viewport or a task
        if cache().vwtask[row] is not None:
            SelectedTasks().info()
            return
        else:
            port = viewport.ViewPort.from_line(row, cache())
            if port is not None:
                Meta().inspect_viewport()
            return

        # No link detected, not a viewport or a task, so delegate to
        # VimwikiFollowLink for link creation
vim.command('VimwikiFollowLink')
```

The second return needs some space(s) :)

**Comment by tbabej** [comment] 2017-02-06 15:05
Thanks for catching this. I pushed a commit to fix the issue, but you could as well submit a PR yourself :) Let me know if it solved the issue for you, so that we can close this.

**Comment by BonarBeavis** [comment] 2017-02-06 16:13
Thank you, it works fine now. And next time with a PR.

**Closed** 2017-02-06 16:22 UTC
